name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install dpl
        run: gem install dpl

      - name: Deploy
        env:
          PROVIDER: ${{ secrets.PROVIDER }}
          APP: ${{ secrets.APP }}
          API_KEY: ${{ secrets.API_KEY }}
        run: dpl --provider="$PROVIDER" --app="$APP" --api-key="$API_KEY"
